### ISSUE TITLE
Spot instances are not joined to a fresh eks 1.18.9 cluster.

### ISSUE THREAD

**Issue by dmitry-mightydevops** [terraform-aws-modules/terraform-aws-eks#1180]
# I have issues

## I'm submitting a...

* [x] bug report

## What is the current behavior?

**Spot** instance workers are not joined to the cluster after the fresh cluster is created

```
➜ k get nodes      
No resources found in default namespace.
```

However autoscaling group is created, and spot instances are fulfilled by the was

**aws autoscaling describe-auto-scaling-groups --auto-scaling-group-names team-shared-eks-python-spot-pool20210109234259660100000003 --output yaml**

```yaml
AutoScalingGroups:
- AutoScalingGroupARN: arn:aws:autoscaling:us-west-2:xxx:autoScalingGroup:ba201f3a-7f31-46e1-9ae0-d3f79e88cad2:autoScalingGroupName/team-shared-eks-python-spot-pool20210109234259660100000003
  AutoScalingGroupName: team-shared-eks-python-spot-pool20210109234259660100000003
  AvailabilityZones:
  - us-west-2a
  - us-west-2b
  - us-west-2c
  CreatedTime: '2021-01-09T23:43:01.090000+00:00'
  DefaultCooldown: 300
  DesiredCapacity: 2
  EnabledMetrics: []
  HealthCheckGracePeriod: 300
  HealthCheckType: EC2
  Instances:
  - AvailabilityZone: us-west-2a
    HealthStatus: Healthy
    InstanceId: i-0ba3f2a68d9ac97ca
    InstanceType: m5zn.xlarge
    LaunchTemplate:
      LaunchTemplateId: lt-082d805d4c211fc09
      LaunchTemplateName: team-shared-eks-python-spot-pool20210109234258967300000001
      Version: '1'
    LifecycleState: InService
    ProtectedFromScaleIn: false
  - AvailabilityZone: us-west-2c
    HealthStatus: Healthy
    InstanceId: i-0cdbbd376065ce8f4
    InstanceType: m5zn.xlarge
    LaunchTemplate:
      LaunchTemplateId: lt-082d805d4c211fc09
      LaunchTemplateName: team-shared-eks-python-spot-pool20210109234258967300000001
      Version: '1'
    LifecycleState: InService
    ProtectedFromScaleIn: false
  LoadBalancerNames: []
  MaxSize: 5
  MinSize: 1
  MixedInstancesPolicy:
    InstancesDistribution:
      OnDemandAllocationStrategy: prioritized
      OnDemandBaseCapacity: 0
      OnDemandPercentageAboveBaseCapacity: 0
      SpotAllocationStrategy: lowest-price
      SpotInstancePools: 5
    LaunchTemplate:
      LaunchTemplateSpecification:
        LaunchTemplateId: lt-082d805d4c211fc09
        LaunchTemplateName: team-shared-eks-python-spot-pool20210109234258967300000001
        Version: $Latest
      Overrides:
      - InstanceType: m5.xlarge
      - InstanceType: m5a.xlarge
      - InstanceType: m5zn.xlarge
  NewInstancesProtectedFromScaleIn: false
  ServiceLinkedRoleARN: arn:aws:iam::xxx:role/aws-service-role/autoscaling.amazonaws.com/AWSServiceRoleForAutoScaling
  SuspendedProcesses:
  - ProcessName: AZRebalance
    SuspensionReason: User suspended at 2021-01-09T23:43:48Z
  Tags:
  - Key: Name
    PropagateAtLaunch: true
    ResourceId: team-shared-eks-python-spot-pool20210109234259660100000003
    ResourceType: auto-scaling-group
    Value: team-shared-eks-python-spot-pool-eks_asg
  - Key: created-by
    PropagateAtLaunch: true
    ResourceId: team-shared-eks-python-spot-pool20210109234259660100000003
    ResourceType: auto-scaling-group
    Value: DmitrySemenov
  - Key: environment
    PropagateAtLaunch: true
    ResourceId: team-shared-eks-python-spot-pool20210109234259660100000003
    ResourceType: auto-scaling-group
    Value: prod
  - Key: kubernetes.io/cluster/team-shared-eks
    PropagateAtLaunch: true
    ResourceId: team-shared-eks-python-spot-pool20210109234259660100000003
    ResourceType: auto-scaling-group
    Value: owned
  - Key: project
    PropagateAtLaunch: true
    ResourceId: team-shared-eks-python-spot-pool20210109234259660100000003
    ResourceType: auto-scaling-group
    Value: infra
  - Key: team
    PropagateAtLaunch: true
    ResourceId: team-shared-eks-python-spot-pool20210109234259660100000003
    ResourceType: auto-scaling-group
    Value: team
  - Key: terraform
    PropagateAtLaunch: true
    ResourceId: team-shared-eks-python-spot-pool20210109234259660100000003
    ResourceType: auto-scaling-group
    Value: 'true'
  TargetGroupARNs: []
  TerminationPolicies:
  - Default
  VPCZoneIdentifier: subnet-0fca2356e9d4e1d5f,subnet-0e915781303f5c73e,subnet-0432f9da86d572f8d

```

```
➜ aws ec2 describe-instances  G eks
||||  Arn    |  arn:aws:iam::xxx:instance-profile/team-shared-eks2021010923363674750000000a                                               ||||
|||||  GroupName                  |  team-shared-eks20210109232249263900000003                                                                    |||||
||||  GroupName                  |  team-shared-eks20210109232249263900000003                                                                      ||||
||||  kubernetes.io/cluster/team-shared-eks               |  owned                                                                                 ||||
||||  Name                                                    |  team-shared-eks-python-spot-pool-eks_asg                                          ||||
||||  aws:autoscaling:groupName                               |  team-shared-eks-python-spot-pool20210109234259660100000003                        ||||
||||  Arn    |  arn:aws:iam::xxx:instance-profile/team-shared-eks2021010923363674750000000a                                               ||||
|||||  GroupName                  |  team-shared-eks20210109232249263900000003                                                                    |||||
||||  GroupName                  |  team-shared-eks20210109232249263900000003                                                                      ||||
||||  aws:autoscaling:groupName                               |  team-shared-eks-python-spot-pool20210109234259660100000003                        ||||
||||  Name                                                    |  team-shared-eks-python-spot-pool-eks_asg                                          ||||
||||  kubernetes.io/cluster/team-shared-eks               |  owned    
```

## If this is a bug, how to reproduce? Please include a code sample if relevant.

```
terraform {
  required_version = ">= 0.13.5"

  required_providers {
    aws        = "~> 3.22.0"
    null       = "~> 3.0.0"
    kubernetes = "~> 1.13"
    random     = "~> 2.1"
  }
}

module "eks_label" {
  source     = "git::https://github.com/cloudposse/terraform-null-label.git?ref=0.22.1"
  namespace  = var.team
  name       = var.component
  attributes = ["eks"]
}

data "aws_eks_cluster" "cluster" {
  name = module.eks_cluster.cluster_id
}

data "aws_eks_cluster_auth" "cluster" {
  name = module.eks_cluster.cluster_id
}

data "aws_availability_zones" "available" {
}

provider "kubernetes" {
  host                   = data.aws_eks_cluster.cluster.endpoint
  cluster_ca_certificate = base64decode(data.aws_eks_cluster.cluster.certificate_authority.0.data)
  token                  = data.aws_eks_cluster_auth.cluster.token
  load_config_file       = false
}

# see options in local.tf/workers_group_defaults_defaults
# to understand various options available for worker_groups
# https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/local.tf
# to use spot instances with the cluster:
# https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/spot-instances.md
module "eks_cluster" {
  source          = "terraform-aws-modules/eks/aws"
  cluster_name    = module.eks_label.id
  cluster_version = "1.18"
  subnets         = var.subnets
  vpc_id          = var.vpc_id

  worker_groups_launch_template = [
    {
      name                                 = "python-spot-pool"
      override_instance_types              = ["m5.xlarge", "m5a.xlarge", "m5zn.xlarge"]
      spot_instance_pools                  = 5
      asg_max_size                         = 5
      asg_desired_capacity                 = 2
      root_volume_size                     = 150
      root_encrypted                       = true
      metadata_http_put_response_hop_limit = 10
      kubelet_extra_args                   = "--node-labels=node.kubernetes.io/lifecycle=spot"
      public_ip                            = false
    }
  ]
  tags = merge(var.tags, {
    created-by = var.created_by
  })
}
```
## What's the expected behavior?

New nodes to be added to the cluster automatically once spot instances are provisioned.

## Are you able to fix this problem and submit a PR? Link here if you have already.

No

## Environment details

* Affected module version: 1.13.3
* OS: Fedora 32
* Terraform version: 0.13.5

```
➜ terraform -version                               
Terraform v0.13.5
+ provider registry.terraform.io/hashicorp/aws v3.22.0
+ provider registry.terraform.io/hashicorp/kubernetes v1.13.3
+ provider registry.terraform.io/hashicorp/local v2.0.0
+ provider registry.terraform.io/hashicorp/null v3.0.0
+ provider registry.terraform.io/hashicorp/random v2.3.1
+ provider registry.terraform.io/hashicorp/template v2.2.0
```

## Any other relevant info

If I do something like this

```
worker_groups_launch_template = [
    {
      name                 = "on-demand-pool"
      instance_type        = "t3.small"
      asg_max_size         = 1
      asg_min_size         = 1
      asg_desired_capacity = 1
      root_volume_size     = 150
      kubelet_extra_args   = "--node-labels=workload=app,tech_stack=php"
      public_ip            = false
    },
    {
      name                    = "python-spot-pool"
      override_instance_types = ["m5.xlarge", "m5a.xlarge", "m5zn.xlarge"]
      spot_instance_pools     = 5
      asg_max_size            = 5
      asg_desired_capacity    = 2
      root_volume_size        = 150
      kubelet_extra_args      = "--node-labels=node.kubernetes.io/lifecycle=spot"
      public_ip               = false
    },
  ]
```

then only on-demand-pool workers get created, but not the spot pool workers. 

The user is in the Administrator group

```
➜ aws sts get-caller-identity --output json
{
    "UserId": "xxx",
    "Account": "xxx",
    "Arn": "arn:aws:iam::xxx:user/DmitrySemenov"
}


➜ aws iam list-groups-for-user --user-name DmitrySemenov --output json

{
    "Groups": [
        {
            "Path": "/",
            "GroupName": "Administrators",
            "GroupId": "XXX",
            "Arn": "arn:aws:iam::XXX:group/Administrators",
            "CreateDate": "2018-08-08T13:40:49+00:00"
        }
    ]
}

that group has the following permission policy attached.

{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": "*",
            "Resource": "*"
        }
    ]
}

```
