### ISSUE TITLE
Do Managed Node Groups need aws-auth to join the control plane?

### ISSUE THREAD

**Issue by ado120** [terraform-aws-modules/terraform-aws-eks#1255]
# I have issues

## I'm submitting a...

* [x ] bug report
* [ ] feature request
* [ ] support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?
When using manage_aws_auth = false and creating a node group, I am getting a..
`NodeCreationFailure: Instances failed to join the kubernetes cluster.`

Reading up on the aws docs, it looks like the aws auth needs to be applied to the cluster in order for the nodes to join the control plane which doesn't really make sense to me as I thought the aws auth file was only for cluster rbac.. Does anyone know if this is the case?

## What's the expected behavior?
Cluster should be able to be deployed successfully without applying the aws_auth file at cluster creation

**Comment by Chili-Man** [comment]
@ado120 the `aws-auth` ConfigMap also specifies the AWS node instance role mapping to a Kubernetes group so that it can properly join the cluster. For example, it should have at the minimum something like this:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: <ARN of instance role (not instance profile)>
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes

``` 
You can see some more of the details here https://docs.aws.amazon.com/eks/latest/userguide/add-user-role.html. 

So if you set `manage_aws_auth = false` , you have to ensure that the `aws-auth` has the correct aws role mapped to the kubernetes group for the node, otherwise the nodes will fail to join.
