### ISSUE TITLE
Cannot create ingress when aws-load-balancer-controller is deployed.

### ISSUE THREAD

**Issue by kahirokunn** [terraform-aws-modules/terraform-aws-eks#1828]
Cannot create ingress when aws-load-balancer-controller is deployed.

```
$ kubectl apply -f my-ingress.yaml
```

> Error from server (InternalError): error when creating "my-ingress.yaml": Internal error occurred: failed calling webhook "vingress.elbv2.k8s.aws": Post "https://aws-load-balancer-webhook-service.kube-system.svc:443/validate-networking-v1beta1-ingress?timeout=10s": context deadline exceeded

my-ingress.yaml

```
apiVersion: v1
kind: Namespace
metadata:
  name: echoserver
---
apiVersion: v1
kind: Service
metadata:
  name: echoserver
  namespace: echoserver
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  type: NodePort
  selector:
    app: echoserver
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echoserver
  namespace: echoserver
spec:
  selector:
    matchLabels:
      app: echoserver
  replicas: 1
  template:
    metadata:
      labels:
        app: echoserver
    spec:
      containers:
      - image: gcr.io/google_containers/echoserver:1.4
        imagePullPolicy: Always
        name: echoserver
        ports:
        - containerPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: echoserver
  namespace: echoserver
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/backend-protocol: HTTP
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
spec:
  defaultBackend:
    service:
      name: echoserver
      port:
        number: 80
```

aws-load-balancer-controller will not work properly if you do not allow TCP ingress of 9443 in node_groups.
I will try to add a sample.

Reference: https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/2208
