### ISSUE TITLE
Tag k8s.io/cluster-autoscaler/enabled does not propagate

### ISSUE THREAD

**Issue by ProTip** [terraform-aws-modules/terraform-aws-eks#190]
# I have issues
Getting the autoscaler to detect the ec2 instances and consider them for scale down.

## I'm submitting a...

* [ ] bug report
* [x] feature request
* [ ] support request
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?
This tag is not set to propagate at launch:
https://github.com/terraform-aws-modules/terraform-aws-eks/blob/d5803697792ef36dd8964f67a1ae5184ddbfeb22/workers.tf#L17

The autoscaler's default settings, at least as per the recomended Helm chart installation, looks for the cluster tag _and_ the `enabled` tag on ec2 instances. It does not appear to check the instances if both tags are not present(the ASG is picked up, but instances without both tags do not appear in the log output for unneeded checks).

## What's the expected behavior?
The tag would be set to propagate at launch.

**Comment by max-rocket-internet** [comment]
Are you sure that's why your ASG is not being scaled down?

I have this config for the autoscaler helm chart:

```
autoDiscovery:
  clusterName: my-cluster
  enabled: true

extraArgs:
  v: 1
  logtostderr: "true"
  expander: "least-waste"
  skip-nodes-with-system-pods: "false"
```

In EKS workgroup:

```
  worker_groups = [
    {
      instance_type       = "m4.xlarge"
      key_name            = "rps-default"
      asg_max_size        = 40
      autoscaling_enabled = true
```

And scale down works fine.
