### ISSUE TITLE
userdata templates don't allow cloud-init directives

### ISSUE THREAD

**Issue by onoffleftright** [terraform-aws-modules/terraform-aws-eks#195]
# I have issues

## I'm submitting a...

* [ ] bug report
* [x] feature request
* [ ] support request
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?

`userdata.sh.tpl` is written to assume written to assume all userdata values are written in bash, but Amazon Linux 2 supports cloud-init directives to be passed in the user_data attribute using `multipart/mixed` Content-Type headers. Everything passed in via `pre_userdata` and `additional_userdata` current has to be written in bash.

## What's the expected behavior?

`pre_userdata` and `additional_userdata` should support multiple cloud-init directives or bash scripts. Each segment is differentiated via `Content-Type` headers.

For example, to support a cloud-init directive to create a custom user, and then to run a bash script to run `yum update`, a userdata value (provided via either `pre_userdata` and `additional_userdata`) could look like this:

```
--==BOUNDARY==
Content-Type: text/cloud-config; charset="us-ascii"

#cloud-config
cloud_final_modules:
- [users-groups,always]
users:
  - name: custom_user
    groups: [ wheel ]
    sudo: [ "ALL=(ALL) NOPASSWD:ALL" ]
    shell: /bin/bash

--==BOUNDARY==
Content-Type: text/x-shellscript; charset="us-ascii"
#!/bin/bash

yum update -y
```

## Are you able to fix this problem and submit a PR? Link here if you have already.

Yes.

## Environment details

* Affected module version: v1.7.0
* OS: Amazon Linux 2
* Terraform version: n/a

## Any other relevant info
n/a
