### ISSUE TITLE
YAML Interpolation for Auth ConfigMap

### ISSUE THREAD

**Issue by thinkbiggerltd** [terraform-aws-modules/terraform-aws-eks#2022]
## Description

I am using the latest release of the Terraform EKS Module (v18.20.2), where I am attempting to use the newly added  aws-auth configmap functionality, added om 18.20.0.

https://registry.terraform.io/modules/terraform-aws-modules/eks/aws/latest

The funtionality works, in so far as it is populating and updating the  aws-auth configmap but the interpolation doesn't appear correct. As a result no access is being granted by the configmap. It appears that the yaml encoding of the configmap is not rendering correctly, leaving "" quotes in place in the YAML code.

## Versions

- Module version [Required]:
```hcl
terraform {
  required_version = ">= 0.13.1"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = ">= 3.72"
    }
    kubernetes = {
      source  = "hashicorp/kubernetes"
      version = ">= 2.10"
    }
  }
}
```

## Reproduction Code [Required]
```hcl
  # aws-auth configmap
  manage_aws_auth_configmap = true

  aws_auth_roles = [
    {
      rolearn  = "arn:aws:iam::88888888888::role/AWSReservedSSO_AWSReadOnlyAccess"
      username = "readonly"
      groups   = ["system:masters"]
    },
  ]
```

Plan/Apply succeeds and configmap is updated but access is not working. Details below in ## Actual behavior

## Expected behavior

``` yaml
  mapRoles: |-
    - rolearn: arn:aws:iam::88888888888::role/eks-managed-nodegroup-spot
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
    - rolearn: arn:aws:iam::88888888888::role/AWSReservedSSO_AWSReadOnlyAccess
      username: build
      groups:
        - system:masters
```
## Actual behavior
```yaml
  mapRoles: |
    - "groups":
      - "system:bootstrappers"
      - "system:nodes"
      "rolearn": "arn:aws:iam::88888888888:role/eks-managed-nodegroup-spot"
      "username": "system:node:{{EC2PrivateDNSName}}"
    - "groups":
      - "system:masters"
      "rolearn": "arn:aws:iam::88888888888:role/aws-reserved/sso.amazonaws.com/AWSReservedSSO_AWSReadOnlyAccess"
      "username": "readonly"
```
