### ISSUE TITLE
Adding `map_roles` prevents worker nodes from joining cluster

### ISSUE THREAD

**Issue by bobby** [terraform-aws-modules/terraform-aws-eks#206]
# I have issues

## I'm submitting a...

* [x] bug report
* [ ] feature request
* [ ] support request
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?

When I add to `map_roles`, new worker nodes fail to join the cluster.  When I comment-out `map_roles`, worker nodes are again able to join the cluster.

## If this is a bug, how to reproduce? Please include a code sample if relevant.

I added:

```
  map_roles = [
    {
      role_arn = "${data.aws_iam_role.power_user.arn}"
      username = "power_user"
      group    = "system:masters"
    }
  ]
```

and new nodes failed to join the cluster.  Upon commenting out the same, a fresh batch of new nodes were able to join.

## What's the expected behavior?

I should be able to add customer roles to `map_roles` without disrupting the existing cluster-worker IAM role.

## Environment details

* Affected module version: 1.8.0
* OS: Linux
* Terraform version: 0.11.10

## Any other relevant info

config-map-aws-auth_cp-staging.yaml:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::<account-id>:role/cp-staging201812<snip>
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes

    - rolearn: arn:aws:iam::<account-id>:role/<redacted role name>
      username: power_user
      groups:
        - system:masters

  mapUsers: |

  mapAccounts: |
```

**Comment by max-rocket-internet** [comment]
Is it because you have a role without something `{{xxx}}` in it? i.e the `username` for your role is not like the examples in `aws-iam-authenticator`? e.g. see here: https://github.com/kubernetes-sigs/aws-iam-authenticator/blob/master/README.md

You can see they omit the `{{xxx}}` when configuring a user but not role. So maybe try something like `username: power_user:{{SessionName}}`?

**Comment by max-rocket-internet** [comment]
I'm gonna close this now. Feel free to reopen if it's still an issue.

**Comment by bobby** [comment]
I'm not sure that's the issue, though I'm happy to try out the suggestion.

The aws-iam-authenticator README.md contains these lines:

``` yaml
 # each mapRoles entry maps an IAM role to a username and set of groups
  # Each username and group can optionally contain template parameters:
  #  1) "{{AccountID}}" is the 12 digit AWS ID.
  #  2) "{{SessionName}}" is the role session name.
  mapRoles:
  # statically map arn:aws:iam::000000000000:role/KubernetesAdmin to cluster admin
  - roleARN: arn:aws:iam::000000000000:role/KubernetesAdmin
    username: kubernetes-admin
    groups:
    - system:masters
```

Which seems to indicate that the variable interpolation is optional, and which gives an example in the same shape as mine above.
