### ISSUE TITLE
aws-auth invalid on managed_node_group

### ISSUE THREAD

**Issue by btsteve** [terraform-aws-modules/terraform-aws-eks#2185]
## Description

When Creating a cluster with a managed node group , and aws_auth_roles the resulting aws-auth configmap is invalid. The Nodegroup and the aws_auth_roles seem to be intending the aws_aws_auth_roles too far. 

- [X ] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version [Required]:

- Terraform version:

Terraform v1.2.6
on darwin_arm64
+ provider registry.terraform.io/hashicorp/aws v4.24.0
+ provider registry.terraform.io/hashicorp/cloudinit v2.2.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.12.1
+ provider registry.terraform.io/hashicorp/tls v3.4.0

## Reproduction Code [Required]

```terraform
module "eks" {
  source                          = "terraform-aws-modules/eks/aws"
  version                         = "18.26.6"
  cluster_name                    = local.cluster_name
  cluster_version                 = "1.21"
  cluster_enabled_log_types       = local.cluster_enabled_log_types
  cluster_endpoint_private_access = true
  cluster_endpoint_public_access  = true
  create                          = true
  enable_irsa                     = true
  vpc_id                          = module.vpc.VPC
  iam_role_additional_policies    = ["arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy"]
  cluster_encryption_config = [{
    resources        = ["secrets"]
    provider_key_arn = "arn:aws:kms:us-east-1:xxxxxxxxxxxx:key/xxxxxxxxxxxx"
  }]
  subnet_ids = [
    module.vpc.SubnetAPrivate,
    module.vpc.SubnetBPrivate,
    module.vpc.SubnetDPrivate
  ]
  control_plane_subnet_ids = [
    module.vpc.SubnetAPublic,
    module.vpc.SubnetBPublic,
    module.vpc.SubnetDPublic
  ]
  node_security_group_ntp_ipv4_cidr_block = ["169.254.169.123/32"]
  node_security_group_additional_rules = {
    ingress_self_all = {
      description = "Node to node all ports/protocols"
      protocol    = "-1"
      from_port   = 0
      to_port     = 0
      type        = "ingress"
      self        = true
    }
    egress_all = {
      description      = "Node all egress"
      protocol         = "-1"
      from_port        = 0
      to_port          = 0
      type             = "egress"
      cidr_blocks      = ["0.0.0.0/0"]
      ipv6_cidr_blocks = ["::/0"]
    }
  }
  aws_auth_roles = [var.map_roles]
  cluster_addons = {
    coredns = {
      resolve_conflicts = "OVERWRITE"
    }
    kube-proxy = {}
    vpc-cni = {
      resolve_conflicts        = "OVERWRITE"
      service_account_role_arn = module.vpc_cni_irsa.iam_role_arn
    }
    aws-ebs-csi-driver = {
      resolve_conflicts = "OVERWRITE"

    }
  }
  cluster_tags = {
    Name        = "dev-shared"
    environment = "dev"
  }
  manage_aws_auth_configmap = true
  # create_aws_auth_configmap = true
  cluster_security_group_additional_rules = {
    egress_nodes_ephemeral_ports_tcp = {
      description                = "To node 1025-65535"
      protocol                   = "tcp"
      from_port                  = 1025
      to_port                    = 65535
      type                       = "egress"
      source_node_security_group = true
    }
  }
  eks_managed_node_group_defaults = {
    ami_type                   = "AL2_x86_64"
    instance_types             = local.instance_types
    iam_role_attach_cni_policy = true
  }
  eks_managed_node_groups = {

    default_node_group = {
      create_launch_template = false
      launch_template_name   = ""
      disk_size              = 200
      capacity_type          = "SPOT"
      min_capacity           = 2
      max_capacity           = 10
      remote_access = {
        ec2_ssh_key = local.ssh_key_name

      }
      iam_role_additional_policies = [
        # Required by Karpenter
        "arn:${local.partition}:iam::aws:policy/AmazonSSMManagedInstanceCore"
      ]
      k8s_labels = {
        Environment = "${local.environment}"
      }
      tags = {
        EKS_CLUSTER                                   = "${local.cluster_name}"
        "karpenter.sh/discovery${local.cluster_name}" = local.cluster_name
      }
    }
    # bottlerocket_default = {
    #   # By default, the module creates a launch template to ensure tags are propagated to instances, etc.,
    #   # so we need to disable it to use the default template provided by the AWS EKS managed node group service
    #   create_launch_template = false
    #   launch_template_name   = ""
    #   capacity_type          = "SPOT"
    #   min_capacity           = 2
    #   max_capacity           = 10
    #   remote_access = {
    #     ec2_ssh_key = local.ssh_key_name

    #   }
    #   iam_role_additional_policies = [
    #     # Required by Karpenter
    #     "arn:${local.partition}:iam::aws:policy/AmazonSSMManagedInstanceCore"
    #   ]
    #   k8s_labels = {
    #     Environment = "${local.environment}"
    #   }
    #   ami_type = "BOTTLEROCKET_x86_64"
    #   platform = "bottlerocket"
    #   tags = {
    #     EKS_CLUSTER              = "${local.cluster_name}"
    #     "karpenter.sh/discovery${local.cluster_name}" = local.cluster_name
    #   }
    # }
  }
}
```

Create Cluster with aws_auth_roles with variable
`variable "map_roles" {
  description = "Additional IAM roles to add to the aws-auth configmap."
  type = list(object({
    rolearn  = string
    username = string
    groups   = list(string)
  }))

  default = [
    {
      rolearn  = "arn:aws:iam::xxxxxxxxxxxx:role/okta-xxxxx-dev-readonly-role"
      username = "{{SessionName}}"
      groups   = ["system:masters"]
    },
    {
      rolearn  = "arn:aws:iam::xxxxxxxxxxxx:role/okta-xxxxx-dev-atl-core-dev"
      username = "{{SessionName}}"
      groups   = ["system:masters"]
    },
    {
      rolearn  = "arn:aws:iam::xxxxxxxxxxxx:role/jenkins_k8s_dev_role"
      username = "{{SessionName}}"
      groups   = ["system:masters"]
    },
  ]
}`
## Expected behavior

```yaml
mapRoles: |
    - "groups":
      - "system:bootstrappers"
      - "system:nodes"
      "rolearn": "arn:aws:iam::xxxxxxxxx:role/default_node_group-eks-node-group-20220802151454779200000005"
      "username": "system:node:{{EC2PrivateDNSName}}"
    - "groups":
      - "system:masters"
      "rolearn": "arn:aws:iam::xxxxxxxxx:role/okta-xxxxxx-dev-readonly-role"
      "username": "{{SessionName}}"
    - "groups":
      - "system:masters"
      "rolearn": "arn:aws:iam::xxxxxxxxx:role/okta-xxxxxx-dev-atl-core-dev"
      "username": "{{SessionName}}"
    - "groups":
      - "system:masters"
      "rolearn": "arn:aws:iam::xxxxxxxxx:role/jenkins_k8s_dev_role"
      "username": "{{SessionName}}"
````

## Actual behavior

``` yaml
mapRoles: |
    - "groups":
      - "system:bootstrappers"
      - "system:nodes"
      "rolearn": "arn:aws:iam::xxxxxxxxx:role/default_node_group-eks-node-group-20220802151454779200000005"
      "username": "system:node:{{EC2PrivateDNSName}}"
    - - "groups":
        - "system:masters"
        "rolearn": "arn:aws:iam::xxxxxxxxx:role/okta-xxxxxx-dev-readonly-role"
        "username": "{{SessionName}}"
      - "groups":
        - "system:masters"
        "rolearn": "arn:aws:iam::xxxxxxxxx:role/okta-xxxxxx-dev-atl-core-dev"
        "username": "{{SessionName}}"
      - "groups":
        - "system:masters"
        "rolearn": "arn:aws:iam::xxxxxxxxx:role/jenkins_k8s_dev_role"
        "username": "{{SessionName}}"
```
