### ISSUE TITLE
Support for aws-auth in terraform enterprise

### ISSUE THREAD

**Issue by wstewartii** [terraform-aws-modules/terraform-aws-eks#226]
## I'm submitting a...

* [ ] bug report
* [ ] feature request
* [ x] support request
* [ ] kudos, thank you, warm fuzzy

I'd like to have terraform enterprise automatically apply the aws-auth ConfigMap after provisioning an eks cluster. Currently it's required to add the aws-iam-authenticator to your PATH and have kubectl available. The enterprise version of terraform doesn't allow me the flexibility to install binaries or touch the folders in the $PATH environment variable. I'd like to know if there are any plans to add support for this or if there is a recommended workaround.

**Comment by max-rocket-internet** [comment]
You can also just change your `KUBECONFIG` to a path of your choosing, right?

e.g.

```yaml
...
users:
- name: my-cluster
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      command: /my/path/to/aws-iam-authenticator
      args:
        - "token"
        - "-i"
        - "my-cluster"
```
