### ISSUE TITLE
Managed Group ASG gets dynamic scaling policy attached to it

### ISSUE THREAD

**Issue by icicimov** [terraform-aws-modules/terraform-aws-eks#2285]
## Description

When creating a Managed Group I get a Dynamic Scaling Policy attached to it. The policy has the following parameters:

```
eks-nodes-xxxxx-autoscaling-policy
Target tracking scaling
As required to maintain Average CPU utilization at 30
Add or remove capacity units as required
0 seconds to warm up before including in metric
```

which clashes with Cluster Autoscaler add-on and causes cluster instability due to number of nodes constantly flip-flopping due to the Policy and CAS fighting each other over the ASG capacity. I have searched for a parameter in the Module that I can use to disable the Policy creation for the Managed Group but I can not find one (apologies beforehand if one exists and I missed it somehow).

- [x] ✋ I have searched the open/closed issues and my issue is not listed.

This https://github.com/terraform-aws-modules/terraform-aws-eks/issues/2089 was the closest issue I could find and according to it there is nothing we can do on the module side to prevent this from happening?

## Versions

- Module version [Required]: version = "~> 18.26.6"
- Terraform version: 1.1.9
- Provider version(s): 
   "hashicorp/aws" : version = "~> 4.25.0"
   "hashicorp/kubernetes": version = "2.12.1"
   "hashicorp/time": version = "0.7.2"
    "hashicorp/tls": version = "3.4.0"

## Reproduction Code [Required]

This is my module definition:

```
locals {
  remote_access_lc = var.cluster_ssh_access ? {
    remote_access = {
      ec2_ssh_key               = var.key_name
      source_security_group_ids = [module.bastion[0].bastion_sg_id]
    }
  } : { 
    remote_access = {
      ec2_ssh_key               = null
      source_security_group_ids = null
    }
  }
}

module "eks" {
  source  = "terraform-aws-modules/eks/aws"
  version = "~> 18.26.6"

  cluster_name                    = var.k8s_cluster
  cluster_version                 = var.cluster_version

  cluster_endpoint_private_access = var.cluster_endpoint_private_access
  cluster_endpoint_public_access  = var.cluster_endpoint_public_access
  cluster_endpoint_public_access_cidrs = var.cluster_endpoint_public_access_cidrs

  cluster_enabled_log_types       = var.cluster_enabled_log_types

  vpc_id                          = module.vpc.vpc_id
  subnet_ids                      = flatten([for i in range(var.vpc["priv_subnet_sets"]) : module.private-subnets[i].subnet_ids])

  create_aws_auth_configmap = var.create_aws_auth_configmap
  manage_aws_auth_configmap = var.manage_aws_auth_configmap
  aws_auth_roles            = concat(local.admin_user_map_roles, local.developer_user_map_roles)

  eks_managed_node_group_defaults = var.eks_managed_node_group_defaults
  eks_managed_node_groups = { for k in keys(var.eks_managed_node_groups) : k => merge(var.eks_managed_node_groups[k], local.remote_access_lc) }

  self_managed_node_group_defaults = var.self_managed_node_group_defaults
  self_managed_node_groups         = var.self_managed_node_groups

  cluster_addons = {
    coredns = {
      addon_version     = var.coredns_addon_version
      resolve_conflicts = "OVERWRITE"
    }
    kube-proxy = {
      addon_version     = var.kube_proxy_addon_version
      resolve_conflicts = "OVERWRITE"
    }
    vpc-cni = {
      addon_version     = var.vpc_cni_addon_version
      resolve_conflicts = "OVERWRITE"
    }
  }

  node_security_group_additional_rules = {
    # https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/2039#issuecomment-1099032289
    ingress_allow_access_from_control_plane = {
      description                   = "Allow access from control plane to webhook port of AWS load balancer controller"
      type                          = "ingress"
      protocol                      = "tcp"
      from_port                     = 9443
      to_port                       = 9443
      source_cluster_security_group = true
    }
  }
}
```
and these are my vars settings:

```
eks_managed_node_group_defaults = {
  ami_type       = "AL2_x86_64"
  disk_size      = 100
  instance_types = ["m6i.large", "m5.large", "m5n.large", "m5zn.large"]
  iam_role_additional_policies = [
    "arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy",
    "arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy",
    "arn:aws:iam::aws:policy/ElasticLoadBalancingFullAccess",
    <some custom policies>
  ]
  iam_role_attach_cni_policy = true
}

eks_managed_node_groups = {
  "nodes" = {
    ami_type     = "AL2_x86_64"
    min_size     = 3
    max_size     = 40
    desired_size = 3
    instance_types = [
      "r5.4xlarge",
      "r5.2xlarge"
    ]
    capacity_type = "ON_DEMAND"
    network_interfaces = [{
      delete_on_termination       = true
      associate_public_ip_address = true
    }]
    # By default, the module creates a launch template to ensure tags are propagated to instances, etc.,
    # so we need to disable it to use the default template provided by the AWS EKS managed node group service
    create_launch_template = false
    launch_template_name   = ""

    labels = {
      role = "workers"
    }

    update_config = {
      max_unavailable  = 1
    }
  }
}
```

## Expected behavior

Well unexpected to me was to see a Dynamic Scaling Policy attached to the Managed Group ASG that scales up/down the node group based on CPU threshold of 30%. Where did this come from?

## Additional context

Just to mention, when I create an EKS cluster using `eksctl` I do not see this behavior i.e. the ASG policy does not get created. Example config from cluster YAML:

```
managedNodeGroups: 
  - amiFamily: AmazonLinux2
    desiredCapacity: 3
    iam:
      attachPolicyARNs:
      - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
      - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
      - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
      - arn:aws:iam::aws:policy/ElasticLoadBalancingFullAccess
      - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
      withAddonPolicies:
        albIngress: true
        autoScaler: true
        awsLoadBalancerController: true
        certManager: true
        cloudWatch: true
        ebs: true
        efs: true
        externalDNS: true
    instanceType: r5.2xlarge
    labels:
      role: workers
    maxSize: 20
    minSize: 3
    name: nodes
    privateNetworking: true
    ssh:
      allow: true
      publicKeyPath: ./eks/ssh.pem
    tags:
      k8s.io/cluster-autoscaler/enabled: "true"
      k8s.io/cluster-autoscaler/eks-cluster: owned
    volumeEncrypted: false
    volumeSize: 100
    volumeType: gp3
```
