### ISSUE TITLE
Unable to kubectl into a new EKS cluster with AWS SSO due to `(Unauthorized)`

### ISSUE THREAD

**Issue by lordgordon** [terraform-aws-modules/terraform-aws-eks#2292]
## Description

I created a new EKS cluster (kubernetes 1.23) re-using a configuration I have for an existing and working EKS cluster (still on kubernetes 1.21). In the new cluster I'm unable to run any `kubectl` commands due to:

```
error: You must be logged in to the server (Unauthorized)
```

I'm using AWS SSO. 

- [X] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version: `18.30.2`

- Terraform version:
```
Terraform v1.3.3
on darwin_arm64
+ provider registry.terraform.io/hashicorp/aws v3.75.2
+ provider registry.terraform.io/hashicorp/cloudinit v2.2.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.14.0
+ provider registry.terraform.io/hashicorp/random v3.1.3
+ provider registry.terraform.io/hashicorp/tls v4.0.3
```

## Reproduction Code

```terraform
data "aws_caller_identity" "current" {}

module "eks" {
  source  = "terraform-aws-modules/eks/aws"
  version = "18.30.2"

  cluster_name    = "test"
  cluster_version = "1.23"
  #subnet_ids      = module.vpc.private_subnets
  #vpc_id          = module.vpc.vpc_id

  cluster_enabled_log_types = ["audit", "api", "authenticator", "controllerManager", "scheduler"]

  cluster_addons = var.cluster_addons

  eks_managed_node_groups = {
    main = {
      name                = "eks-node-main"
      instance_types      = ["t3a.small"]
      ami_release_version = "1.23.9-20221101"

      desired_size = 1
      min_size     = 1
      max_size     = 1

      capacity_type = "ON_DEMAND"

      block_device_mappings = {
        xvda = {
          device_name = "/dev/xvda"
          ebs = {
            volume_size           = 50
            volume_type           = "gp2"
            encrypted             = false
            delete_on_termination = true
          }
        }
      }

      create_launch_template                 = true
      update_launch_template_default_version = true

      update_config = {
        max_unavailable = 1
      }
    }
  }

  prefix_separator                   = ""
  iam_role_name                      = "test"
  cluster_security_group_name        = "test"
  cluster_security_group_description = "EKS cluster security group."

  cluster_security_group_additional_rules = {
    egress_nodes_ephemeral_ports_tcp = {
      description                = "To node 1025-65535"
      protocol                   = "tcp"
      from_port                  = 1025
      to_port                    = 65535
      type                       = "egress"
      source_node_security_group = true
    }
  }

  node_security_group_additional_rules = {
    ingress_self_all = {
      description = "Node to node all ports/protocols"
      protocol    = "-1"
      from_port   = 0
      to_port     = 0
      type        = "ingress"
      self        = true
    }

    egress_all = {
      description      = "Node all egress"
      protocol         = "-1"
      from_port        = 0
      to_port          = 0
      type             = "egress"
      cidr_blocks      = ["0.0.0.0/0"]
      ipv6_cidr_blocks = ["::/0"]
    }
  }
}

resource "kubernetes_config_map_v1" "aws_auth" {
  metadata {
    name      = "aws-auth"
    namespace = "kube-system"
    labels = {
      "app.kubernetes.io/managed-by" : "Terraform"
      "terraform.io/module" : "terraform-aws-modules.eks.aws"
    }
  }

  data = {
    mapRoles = yamlencode(concat(
      [for role in var.aws_iam_roles_with_k8s_admin_access :
        {
          rolearn  = "arn:aws:iam::${data.aws_caller_identity.current.account_id}:role/${role}"
          username = "admin"
          groups   = ["system:masters"]
        }
      ],
      [for group in module.eks.eks_managed_node_groups :
        {
          rolearn  = group.iam_role_arn
          username = "system:node:{{EC2PrivateDNSName}}"
          groups   = ["system:bootstrappers", "system:nodes"]

      }]
    ))
  }
}

data "aws_eks_cluster" "cluster" {
  name = module.eks.cluster_id
}

provider "kubernetes" {
  host                   = data.aws_eks_cluster.cluster.endpoint
  cluster_ca_certificate = base64decode(data.aws_eks_cluster.cluster.certificate_authority.0.data)

  exec {
    api_version = "client.authentication.k8s.io/v1"
    command     = "aws"
    args = [
      "eks",
      "get-token",
      "--cluster-name",
      data.aws_eks_cluster.cluster.name
    ]
  }
}

```

where `aws_iam_roles_with_k8s_admin_access` is:
```terraform
aws_iam_roles_with_k8s_admin_access = [
    "AWSReservedSSO_AdministratorAccess_***",
  ]
```

1. `terraform apply`
2. waiting the cluster to be up and running
3. run `terraform apply` again to update `aws-auth` after cluster creation
4. start my AWS SSO session with the `AdministratorAcces` Role
5. `kubectl get pods`

### Details

From AWS EKS Console interface I can confirm the `aws-auth` is correctly applied. The `mapRoles` tab shows:
```yaml
- "groups":
  - "system:masters"
  "rolearn": "arn:aws:iam::***:role/AWSReservedSSO_AdministratorAccess_***"
  "username": "admin"
- "groups":
  - "system:bootstrappers"
  - "system:nodes"
  "rolearn": "arn:aws:iam::***:role/eks-node-main-eks-node-group-***"
  "username": "system:node:{{EC2PrivateDNSName}}"
``` 

From CloudWatch I found this log:
```
time="2022-11-07T09:33:04Z" level=info msg="STS response" accesskeyid=*** 
accountid=*** arn="arn:aws:sts::***:assumed-role/AWSReservedSSO_AdministratorAccess***/myuser" 
client="127.0.0.1:59140" method=POST path=/authenticate 
session=myuser userid=***

time="2022-11-07T09:33:04Z" level=info msg="access granted" arn="arn:aws:iam::***:role/AWSReservedSSO_AdministratorAccess***" 
client="127.0.0.1:59140" groups="[system:masters]" method=POST path=/authenticate uid="aws-iam-authenticator:***:***" 
username=kubernetes-admin
```

It seems the OICD authentication is working fine, but the `username` is set to the wrong value: `kubernetes-admin` instead of `admin`. In my cluster there is no `kubernetes-admin` ClusterRole, while `admin` exists.

I don't understand why my `map_roles` is not correctly applied, and where that `kubernetes-admin` comes from.

**Comment by lordgordon** [comment]
To clarify, here my kubeconfig:
```yaml
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: ***
    server: https://***.eks.amazonaws.com
  name: test-eks
contexts:
- context:
    cluster: test-eks
    user: aws-sso
  name: test.mydomain.com
current-context: test.mydomain.com
kind: Config
preferences: {}
users:
- name: aws-sso
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1
      args:
      - --region
      - ***
      - eks
      - get-token
      - --cluster-name
      - test
      command: aws
      env: null
      interactiveMode: IfAvailable
      provideClusterInfo: false
```

And the output of `aws sts get-caller-identity` before calling `kubectl commands`:
```json
{
    "UserId": "***:myuser",
    "Account": "***",
    "Arn": "arn:aws:sts::***:assumed-role/AWSReservedSSO_AdministratorAccess_***/myuser"
}
```

This is the same role used to run terraform commands.

**Comment by bryantbiggs** [comment]
IAM role paths are not supported in the aws-auth configmap so you'll need to strip out the path before adding to the configmap

**Comment by lordgordon** [comment]
Thanks, I'll try. That's weird because I have the very same config in another EKS and it works.

**Comment by lordgordon** [comment]
This is what I have in another EKS cluster (with kubernetes 1.21) in `mapRoles`:
```yaml
- "groups":
  - "system:masters"
  "rolearn": "arn:aws:iam::***:role/AWSReservedSSO_AdministratorAccess_***"
  "username": "admin"
- "groups":
  - "system:bootstrappers"
  - "system:nodes"
  "rolearn": "arn:aws:iam::***:role/eks-node-main-eks-node-group-***"
  "username": "system:node:{{EC2PrivateDNSName}}"
```

Here the kubectl auth works fine.
