### ISSUE TITLE
Windows Managed Node Group support

### ISSUE THREAD

**Issue by bryantbiggs** [terraform-aws-modules/terraform-aws-eks#2350]
## Is your request related to a new offering from AWS?
- Yes
	- https://aws.amazon.com/about-aws/whats-new/2022/12/amazon-eks-automated-provisioning-lifecycle-management-windows-containers/
	- https://github.com/aws/containers-roadmap/issues/584#issuecomment-1353809239

## Describe the solution you'd like.
- Ability to create EKS managed node groups with Windows based nodes

## Additional context
- Tangentially to this change, we should evaluate if we can better accommodate `cloud-config` in user-data since we will be making changes to support Windows based instances now
	- https://github.com/terraform-aws-modules/terraform-aws-eks/pull/2335

**Comment by bryantbiggs** [comment]
Requires the Terraform aws-sdk version to be updated https://github.com/hashicorp/terraform-provider-aws/issues/28438

**Comment by chandrasekharkolla** [comment]
Any update on this?

**Comment by bryantbiggs** [comment]
There aren't any code changes required so you can in theory use it today, but we will be adding an example and checking to see how it aligns with the rest of the Linux AL2 and Bottlerocket OS usage

**Comment by sebas-w** [comment]
If you want to create a windows managed node group using this module, I can confirm that on version `18.31.2` you can specify the following for a node group as long as the following requirements are fulfilled.

## Requirements
- You already Have a linux EKS Node Group and nodes on your cluster. I confirmed with AWS Support you're not able to run just a windows EKS Cluster so you need to already have a linux node in place to launch any windows nodes via the Managed Node Group option.
- Your EKS node Role has the policy `AmazonEKSVPCResourceController`, which it should if you use this module since it's (here)[https://github.com/terraform-aws-modules/terraform-aws-eks/blob/a8e0de0b3f3a3e27232b35e9ed8814549273bced/main.tf#L323]; 
- You have enabled the Windows support by adding the configmap:
```yaml
apiVersion: v1
data:
  enable-windows-ipam: "true"
immutable: false
kind: ConfigMap
metadata:
  name: amazon-vpc-cni
  namespace: kube-system
```

## Example

```terraform
eks_managed_node_groups = {
  windows = {
    min_size          = 1
    desired_size      = 1
    max_size          = 5
    platform          = "windows"
    ami_type          = "WINDOWS_CORE_2019_x86_64"
    capacity_type     = "SPOT"
    enable_monitoring = true
    disk_size         = "100"
    use_name_prefix   = true
    cluster_version   = var.aws_eks_cluster_version
    instance_types    = ["m5d.xlarge", "m5ad.xlarge"]
    taints = [
      {
        key    = "os"
        value  = "windows"
        effect = "NO_SCHEDULE"
      }
    ]
  },
},
```

**Comment by bryantbiggs** [comment]
thank you for sharing @sebas-w !

**Comment by enver** [comment]
@sebas-w Thank you for sharing an example!
I was able to create windows managed node pool as you described above and run a test pod on it. However, I'm unable to connect to any pod via the cluster's internal network. Access to other resources in VPC or the internet works without issue (except for obvious DNS resolution problems). Did you have such problems?

**Comment by aamoctz** [comment]
@sebas-w This does indeed work unless you set `var.manage_aws_auth_configmap = true`.
If that var is enabled then the module overwrites `aws-auth` configmap values set by EKS and in the process removes the `eks:kube-proxy-windows` line from the Windows node group in the `aws-auth` configmap.

[local.node_iam_role_arns_windows](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/main.tf#L453-L460) currently does not look at `module.eks_managed_node_groups` to determine if `platform == "windows"`. So the module assumes MNGs are Linux or Bottlerocket and that line in the config is removed.

## When `var.manage_aws_auth_configmap = false`:

```yaml
mapRoles: |
  - "groups":
    - "eks:kube-proxy-windows"
    - "system:bootstrappers"
    - "system:nodes"
    "rolearn": "<windows_mng_role_arn>"
    "username": "system:node:{{EC2PrivateDNSName}}"
```

## When `var.manage_aws_auth_configmap = true`:

```yaml
mapRoles: |
  - "groups":
    - "system:bootstrappers"
    - "system:nodes"
    "rolearn": "<windows_mng_role_arn>"
    "username": "system:node:{{EC2PrivateDNSName}}"
```
