### ISSUE TITLE
Unable to connect to the server: x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by DavideM78** [terraform-aws-modules/terraform-aws-eks#2417]
## Description

Hi everybody and thanks to everyone will give a look into my issue.
I have a running cluster, the only problem is that when I run a Gitlab Pipeline, I got this error:
"Unable to connect to the server: x509: certificate signed by unknown authority

- Terraform version:
Terraform v1.3.7
- Provider version(s):
+ provider registry.terraform.io/hashicorp/cloudinit v2.2.0
+ provider registry.terraform.io/hashicorp/helm v2.7.1
+ provider registry.terraform.io/hashicorp/kubernetes v2.15.0
+ provider registry.terraform.io/hashicorp/tls v4.0.4

## Reproduction Code [Required]

This is a part of the code
data.tf:
```
data "aws_region" "current" {}

data "aws_iam_roles" "sso" {
  name_regex  = "AWSReservedSSO_.*"
  path_prefix = "/aws-reserved/sso.amazonaws.com/"
}

data "aws_eks_cluster" "this" {
  name = module.eks.cluster_id
}

data "aws_eks_cluster_auth" "this" {
  name = module.eks.cluster_id
}

data "aws_lb" "cluster" {
  tags = {
    "elbv2.k8s.aws/cluster" = var.cluster_name
    "service.k8s.aws/stack" = "ingress-nginx/cluster-ingress-ingress-nginx-controller"
  }

  depends_on = [helm_release.ingress_nginx]
}
```

main.tf

```
provider "kubernetes" {
  host                   = data.aws_eks_cluster.this.endpoint
  cluster_ca_certificate = base64decode(data.aws_eks_cluster.this.certificate_authority[0].data)
  token                  = data.aws_eks_cluster_auth.this.token
}

provider "helm" {
  kubernetes {
    host                   = data.aws_eks_cluster.this.endpoint
    cluster_ca_certificate = base64decode(data.aws_eks_cluster.this.certificate_authority[0].data)
    token                  = data.aws_eks_cluster_auth.this.token
  }
}

resource "aws_iam_user" "deployment" {
  name = "Deployment"

  tags = var.tags
}

resource "aws_iam_access_key" "deployment" {
  user = aws_iam_user.deployment.name
}

resource "aws_iam_policy" "deployment" {
  name        = "eks_deployment"
  description = "Policy for deployment IAM user"
  policy = jsonencode(
    {
      Version = "2012-10-17"
      Statement = [
        {
          Action = [
            "eks:DescribeCluster",
            "eks:ListClusters"
          ]
          Effect   = "Allow"
          Resource = "*"
        },
      ]
    }
  )
}

resource "aws_iam_user_policy_attachment" "deployment" {
  user       = aws_iam_user.deployment.name
  policy_arn = aws_iam_policy.deployment.arn
}

resource "aws_kms_key" "eks" {
  description             = "EKS secret encryption key"
  deletion_window_in_days = 7
  enable_key_rotation     = true
  tags                    = var.tags
}

module "eks" {
  source  = "terraform-aws-modules/eks/aws"
  version = "~> 18.30.0"

  cluster_name                    = var.cluster_name
  cluster_version                 = var.cluster_version
  cluster_endpoint_private_access = true
  cluster_endpoint_public_access  = true
  
  # Extend node-to-node security group rules
  node_security_group_additional_rules = {
    ingress_all = {
      description = "Allow HTTP"
      protocol    = "tcp"
      from_port   = 80
      to_port     = 80
      type        = "ingress"
      cidr_blocks      = ["0.0.0.0/0"]
    }
    egress_all = {
      description      = "Allow HTTP"
      protocol         = "tcp"
      from_port        = 80
      to_port          = 80
      type             = "egress"
      cidr_blocks      = ["0.0.0.0/0"]
    }
  }

  cluster_security_group_tags = {
    "kubernetes.io/cluster/${var.cluster_name}" = null
  }

  cluster_addons = {
    coredns = {
      resolve_conflicts = "OVERWRITE"
    }
    kube-proxy = {}
    vpc-cni = {
      resolve_conflicts = "OVERWRITE"
    }
  }

  cluster_encryption_config = [{
    provider_key_arn = aws_kms_key.eks.arn
    resources        = ["secrets"]
  }]

  vpc_id     = var.vpc_id
  subnet_ids = var.private_subnet_ids

  eks_managed_node_group_defaults = {
    ami_type  = "BOTTLEROCKET_x86_64"
    disk_size = 50

    attach_cluster_primary_security_group = true
  }

  eks_managed_node_groups = {
    default = {
      min_size     = var.nodes_min
      max_size     = var.nodes_max
      desired_size = var.nodes_desired

      instance_types = [var.instance_type]
      capacity_type  = var.capacity_type

      subnet_ids = slice(var.private_subnet_ids, 0, var.active_azs)

      update_config = {
        max_unavailable_percentage = 50
      }
    }
  }

  cloudwatch_log_group_retention_in_days = var.cloudwatch_log_group_retention_in_days

  manage_aws_auth_configmap = true

  aws_auth_users = [
    {
      userarn  = aws_iam_user.deployment.arn
      username = aws_iam_user.deployment.name
      groups   = ["system:masters"]
    }
  ]

  aws_auth_roles = [
    for role_arn in data.aws_iam_roles.sso.arns :
    {
      rolearn  = replace(role_arn, "aws-reserved/sso.amazonaws.com/${data.aws_region.current.name}/", "")
      username = regex(".*/AWSReservedSSO_(.*)_.*", role_arn)[0]
      groups   = ["system:masters"]
    }
  ]

  tags = var.tags
}

resource "kubernetes_annotations" "unset_default_storageclass" {
  api_version = "storage.k8s.io/v1"
  kind        = "StorageClass"
  force       = true

  metadata {
    name = "gp2"
  }

  annotations = {
    "storageclass.kubernetes.io/is-default-class" = "false"
  }
}
```

.gitlab-ci-yml:
```
default:
  image:
    name: alpine
    entrypoint: [""]

variables:
  NAMESPACE: test-namespace

stages:
  - deploy

before_script:
  - apk add --update curl
  - curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -L -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"
  - chmod +x kubectl
  - mv kubectl /usr/local/bin/
  - apk add --update py3-pip
  - pip3 install awscli --upgrade
  - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
  - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
  - aws eks --region eu-central-1 update-kubeconfig --name eks-development

deploy:
  stage: deploy
  script:
    - kubectl config set-cluster k8s --server="$CLUSTER_ADDRESS"
    - kubectl config set-credentials deployment-user --username=$AWS_ACCESS_KEY_ID --password=$AWS_SECRET_ACCESS_KEY
    - kubectl config set-context default --cluster=k8s --user=deployment-user --namespace=$NAMESPACE
    - kubectl config use-context default
    - cd ingress_certificate_example/
    - kubectl apply -f -
```

This is the test app that I would like to deploy:
```
apiVersion: v1
kind: Pod
metadata:
  name: test-ingress-pod
  labels:
    app: test-app
spec:
  containers:
  - name: test-ingress-container
    image: nginx:latest
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: test-ingress-service
  labels:
    app: test-app
spec:
  selector:
    app: test-app
  ports:
  - name: http
    port: 80
    targetPort: 80
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt
    acme.cert-manager.io/http01-edit-in-place: "true"
spec:
  tls:
  - hosts: 
    - test-ingress.example.com
    secretName: test-ingress.example.com
  rules:
  - host: test-ingress.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: test-ingress-service
            port:
              name: http
```

   
Deploy Cluster, than deploy the resources with Gitlab-CI pipeline.

When I deploy manually the resources, than I got no error.
The AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY of the created deployment user are defined as variables in Gitlab-CI/CD 

## Expected behavior

Once I provide the container that runs the pipeline with the cluster´s kubeconfig, the pipeline should not fails (as far as I know). 

## Actual behavior

Pipeline Fails.

**Comment by DavideM78** [comment]
Hi @soostdijck, very interesting. In your case I think that the problem is the user that execute the action,  "system:anonymous" , it should be "system:masters", see aws_auth_users and aws_auth_roles in my config.

**Comment by soostdijck** [comment]
Well, a few hours ago I redeployed the cluster and I now have both errors at the same time. Here's to hoping someone has a solution!

**Comment by DavideM78** [comment]
@bryantbiggs do you have any idea where is the problem, where we are wrong and how we can solve?
I would really appreciate any idea/suggestion.

**Comment by b-a-t** [comment]
> Hi @soostdijck, very interesting. In your case I think that the problem is the user that execute the action, "system:anonymous" , it should be "system:masters", see aws_auth_users and aws_auth_roles in my config.

For me "system:anonymous" looks like the token didn't authenticate the user or actually is empty, which brings you to default `system:anonymous` access. Curling to the API endpoint without provided authorization token gives exactly this message.

**Comment by bryantbiggs** [comment]
Its a very interesting setup and hard to say where to even begin. My advice would be to start simple and slowly build back up to the end desired configuration and see if you can identify where the issue originates. There is a lot in your posted configuration that you could simplify.

**Comment by DavideM78** [comment]
Hi guys, I solved the problem. The issue was not referring to the terraform module, but to the pipeline. I defined the AWS Tokens and the Kubeconfig as variables inside Gitlab CI/CD, than I just rewrite my pipeline:

```
default:
  image:
    name: alpine
    entrypoint: [""]

variables:
  NAMESPACE: test-namespace

stages:
  - deploy

before_script:
  - apk add --update curl
  - curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -L -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"
  - chmod +x kubectl
  - mv kubectl /usr/local/bin/
  - apk add --update py3-pip
  - pip3 install awscli --upgrade
  - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
  - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
  - export AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
  #- aws eks --region eu-central-1 update-kubeconfig --name iworks-eks-development
  #- cat ~/.kube/config

deploy:
  stage: deploy
  script:
    #- kubectl config set-cluster k8s --server="$CLUSTER_ADDRESS"
    #- kubectl config set-credentials deployment-user --username=$AWS_ACCESS_KEY_ID --password=$AWS_SECRET_ACCESS_KEY
    #- kubectl config set-context default --cluster=k8s --user=deployment-user --namespace=$NAMESPACE
    #- kubectl config use-context default
    - cd ingress_certificate_example/
    - kubectl --kubeconfig ${KUBECONFIG} -n $NAMESPACE apply -f pod_service_ingress.yaml
```
In that way the pipeline runs without errors and the resources are deployed to the cluster.
