### ISSUE TITLE
expect exactly one securityGroup tagged with kubernetes.io/cluster

### ISSUE THREAD

**Issue by Smana** [terraform-aws-modules/terraform-aws-eks#2468]
## Description

AWS Load balancer controllers doesn' create loadbalancers because it throws this error:
```console
expect exactly one securityGroup tagged with kubernetes.io/cluster...
```

If your request is for a new feature, please use the `Feature request` template.

- [x] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version: 19.7.0
- Terraform version: 1.3.5
- Provider version(s):
+ provider registry.terraform.io/hashicorp/aws v4.54.0
+ provider registry.terraform.io/hashicorp/cloudinit v2.2.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.17.0
+ provider registry.terraform.io/hashicorp/tls v4.0.4

## Reproduction Code

I'm using the following input variables

```hcl
  cluster_name    = local.cluster_name
  cluster_version = local.cluster_version
  # Temporary as for tests purposes
  cluster_endpoint_public_access = true

  cluster_endpoint_public_access = false

  create_cloudwatch_log_group = true
  cluster_enabled_log_types   = ["api", "authenticator", "audit", "scheduler", "controllerManager"]

  cluster_addons = {
    kube-proxy = {
      most_recent = true
    }
    coredns = {
      most_recent = true
    }
    vpc-cni = {
      most_recent = true
    }
  }

  vpc_id                   = dependency.vpc.outputs.vpc_id
  subnet_ids               = dependency.vpc.outputs.private_subnets
  control_plane_subnet_ids = dependency.vpc.outputs.intra_subnets

  manage_aws_auth_configmap = true

  eks_managed_node_group_defaults = {
    ami_type                   = "BOTTLEROCKET_x86_64"
    platform                   = "bottlerocket"
    capacity_type              = "SPOT"
    use_custom_launch_template = false
    force_update_version       = true
  }

  eks_managed_node_groups = {
    initial = {
      name        = "initial"
      description = "Initial EKS managed node group used for karpenter"

      min_size     = 2
      max_size     = 4
      desired_size = 2

      instance_types = ["m6i.large", "m5.large"]

    }
  }

  tags = {
    "karpenter.sh/discovery" = local.cluster_name
  }
```

I deployed the AWS load balancer controller using these Helm charts values:
```yaml
clusterName: xxx-cute-ewe
defaultTags:
 - <company_tags>
replicaCount: 2
resources:
  limits:
    cpu: 200m
    memory: 100Mi
serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::xxx:role....
  name: aws-load-balancer-controller
topologySpreadConstraints:
- labelSelector:
    matchLabels:
      app.kubernetes.io/name: aws-load-balancer-controller
  maxSkew: 1
  topologyKey: topology.kubernetes.io/zone
  whenUnsatisfiable: DoNotSchedule
vpcId: vpc....
```

## Expected behavior

I'm seeing these errors in the AWS load balancer controller logs

```console
aws-load-balancer-controller-5dbf8fbdcf-2v49w aws-load-balancer-controller {"level":"error","ts":1676227908.355689,"logger":"controller.targetGroupBinding","msg":"Reconciler error","reconciler group":"elbv2.k8s.aws","reconciler kind":"Tar
getGroupBinding","name":"k8s-monitori-kubeprom-44eb73b6f2","namespace":"monitoring","error":"expect exactly one securityGroup tagged with kubernetes.io/cluster/xxx-cute-ewe for eni eni-00d3bf3e33a799c18, got: [sg-04fa899796a42fdf6 sg
-0b532af4e3d1bdb1e] (clusterName: xxx-cute-ewe)"}   
```

## Additional context

:warning: When I remove the tag `kubernetes.io/cluster/xxx-cute-ewe: owned` from the SG which has the description "EKS node shared security group" it worked fine

I've seen several issues but I didn't find a clear recommendation on how to avoid this behavior. Could you please give me a hand?

Thanks
