### ISSUE TITLE
Incorrect apiVersion specified in generated kubeconfig causes kubectl error exec plugin: invalid apiVersion "client.authentication.k8s.io/v1alpha1"

### ISSUE THREAD

**Issue by junglie85** [terraform-aws-modules/terraform-aws-eks#2587]
## Description

Creating a new EKS cluster creates an invalid kubeconfig:

```
kubectl --kubeconfig .\kubeconfig_my-eks version --short
Flag --short has been deprecated, and will be removed in the future. The --short output will become the default.
error: exec plugin: invalid apiVersion "client.authentication.k8s.io/v1alpha1"
```

Changing the relevant section in kubeconfig to the following fixed the problem:

```
users:
  - name: eks_my-eks
    user:
      exec:
        apiVersion: client.authentication.k8s.io/v1beta1
        command: aws-iam-authenticator
        args:
          - "token"
          - "-i"
          - "my-eks"
```

The module should generate the kubeconfig with the correct content.

## Versions

- Module version: 17.24.0

- Terraform version:

Terraform v1.4.5
on windows_amd64
+ provider registry.terraform.io/hashicorp/aws v4.64.0
+ provider registry.terraform.io/hashicorp/cloudinit v2.3.2
+ provider registry.terraform.io/hashicorp/kubernetes v2.20.0
+ provider registry.terraform.io/hashicorp/local v2.4.0
+ provider registry.terraform.io/terraform-aws-modules/http v2.4.1
