### ISSUE TITLE
Karpenter sub-module's IAM role doesn't provide the necessary rights for running and removing EC2 instances

### ISSUE THREAD

**Issue by disparo13** [terraform-aws-modules/terraform-aws-eks#2605]
## Description

I know - it MUST work, but it doesn't.

I'm trying to run Karpenter inside the EKS cluster in the account, let's say - 111111111111. IRSA creating a role with such permissions, and I'm not using `terraform-aws-eks` main module to create "my-eks-cluster" - I'm creating it on my own. 

```
{
    "Statement": [
        {
            "Action": [
                "pricing:GetProducts",
                "ec2:DescribeSubnets",
                "ec2:DescribeSpotPriceHistory",
                "ec2:DescribeSecurityGroups",
                "ec2:DescribeLaunchTemplates",
                "ec2:DescribeInstances",
                "ec2:DescribeInstanceTypes",
                "ec2:DescribeInstanceTypeOfferings",
                "ec2:DescribeImages",
                "ec2:DescribeAvailabilityZones",
                "ec2:CreateTags",
                "ec2:CreateLaunchTemplate",
                "ec2:CreateFleet"
            ],
            "Effect": "Allow",
            "Resource": "*",
            "Sid": ""
        },
        {
            "Action": "ec2:RunInstances",
            "Condition": {
                "StringEquals": {
                    "ec2:ResourceTag/karpenter.sh/discovery": "my-eks-cluster"
                }
            },
            "Effect": "Allow",
            "Resource": "arn:aws:ec2:*:111111111111:launch-template/*",
            "Sid": ""
        },
        {
            "Action": "ec2:RunInstances",
            "Effect": "Allow",
            "Resource": [
                "arn:aws:ec2:*::image/*",
                "arn:aws:ec2:*:111111111111:volume/*",
                "arn:aws:ec2:*:111111111111:subnet/*",
                "arn:aws:ec2:*:111111111111:spot-instances-request/*",
                "arn:aws:ec2:*:111111111111:security-group/*",
                "arn:aws:ec2:*:111111111111:network-interface/*",
                "arn:aws:ec2:*:111111111111:instance/*"
            ],
            "Sid": ""
        },
    
            {
            "Action": [
                "ec2:TerminateInstances",
                "ec2:DeleteLaunchTemplate"
            ],
            "Condition": {
                "StringEquals": {
                    "ec2:ResourceTag/karpenter.sh/discovery": "my-eks-cluster"
                }
            },
            "Effect": "Allow",
            "Resource": "*",
            "Sid": ""
        },
```
So Karpenter can run and get spot prices. Still, when I'm trying to scale my deployment, it only can create a launch template but fails to spin up the instance from it with `UnauthorizedOperation: You are not authorized to perform this operation` errors. The workaround is to moving of `ec2:RunInstances` to the 
```
            "Effect": "Allow",
            "Resource": "*",
            "Sid": ""
```
policy section. But when I'm scaling down my deployment, it's again - cannot delete created earlier EC2 instance and template before I moving both `ec2:TerminateInstances` and `ec2:DeleteLaunchTemplate` actions to the same policy section.

## Versions

- Module version [Required]: 19.13.1

- Terraform version:
1.4.2
- Provider version(s):
aws:4.64
- Karpenter version:
0.27.3

## Reproduction Code [Required]

```
module "karpenter" {
  source = "terraform-aws-modules/eks/aws//modules/karpenter"

  cluster_name = module.main_eks[0].eks_cluster["name"]

  create_iam_role = false
  iam_role_arn    = module.main_eks[0].worker_role_arn

  create_instance_profile = false

  irsa_name                 = "mine-karpenter-controller"
  irsa_max_session_duration = 43200

  iam_role_use_name_prefix = false
  irsa_use_name_prefix     = false

  irsa_oidc_provider_arn          = module.main_eks[0].aws_iam_openid_connect_provider["arn"]
  irsa_namespace_service_accounts = ["karpenter:karpenter"]
  
  tags = {
    format("kubernetes.io/cluster/%s", module.main_eks[0].eks_cluster["name"]) = "owned"
    Terraform                                                                  = "true"
  }
}

```

## Expected behavior

Karpenter can run and operate as expected.

## Actual behavior

Karpenter could not operate as expected before some of its policy actions were not allowed with the asterisk ("*") wildcard

**Comment by disparo13** [comment]
UPDATE: I checked the CloudFormation template by the link from the "Getting started" 
[https://karpenter.sh/v0.27.3/getting-started/getting-started-with-karpenter/cloudformation.yaml](https://karpenter.sh/v0.27.3/getting-started/getting-started-with-karpenter/cloudformation.yaml) 

They've used global access to "ec2:DeleteLaunchTemplate", "ec2:RunInstances", "ec2:TerminateInstances" in their role's policy as well.

```
        Statement:
          - Effect: Allow
            Resource: "*"
            Action:
              # Write Operations
              - ec2:CreateFleet
              - ec2:CreateLaunchTemplate
              - ec2:CreateTags
              - ec2:DeleteLaunchTemplate
              - ec2:RunInstances
              - ec2:TerminateInstances
              # Read Operations
              - ec2:DescribeAvailabilityZones
              - ec2:DescribeImages
              - ec2:DescribeInstances
              - ec2:DescribeInstanceTypeOfferings
              - ec2:DescribeInstanceTypes
              - ec2:DescribeLaunchTemplates
              - ec2:DescribeSecurityGroups
              - ec2:DescribeSpotPriceHistory
              - ec2:DescribeSubnets
              - pricing:GetProducts
              - ssm:GetParameter
```
