### ISSUE TITLE
Not possible to specify availability zone for node group

### ISSUE THREAD

**Issue by xgp** [terraform-aws-modules/terraform-aws-eks#2625]
Per https://aws.amazon.com/blogs/containers/amazon-eks-cluster-multi-zone-auto-scaling-groups/ and the API, it is possible to set up a node group within specified availability zones. E.g.
```
nodeGroups:
  - name: ng1
    instanceType: m5.xlarge
    availabilityZones:
      - us-west-2a
```

However, using the `eks_managed_node_group` submodule, it is not possible to specify the availability zones.

Is it possible to add this feature to the terraform module, given that the functionality is already there?
