### ISSUE TITLE
IAM User Credential Rotation Causes Terraform EKS Provider Connection Refused Error

### ISSUE THREAD

**Issue by saiprasanna7** [terraform-aws-modules/terraform-aws-eks#2857]
### Description
When IAM user (cicd) credentials rotated that are used for executing Terraform, the Terraform AWS EKS provider fails to recognize the same user with the previous credentials. This issue is observed during the execution of the Terraform plan. The same user (cicd) is used in the aws-auth config map in the mapUsers section. 

I'm using Kubernetes provider that looks like the below:
```
provider "kubernetes" {
  host                   = module.eks.cluster_endpoint
  cluster_ca_certificate = base64decode(module.eks.cluster_certificate_authority_data)
  exec {
    api_version = "client.authentication.k8s.io/v1beta1"
    command     = "aws"
    # This requires the awscli to be installed locally where Terraform is executed
    args = ["eks", "get-token", "--cluster-name", local.cluster_name]
  }
}
```

aws-auth configmap data block looks like below: 
```
data:
  mapAccounts: |
    []
  mapRoles: |
    - "groups":
      - "system:bootstrappers"
      - "system:nodes"
      "rolearn": "arn:aws:iam::1234567890:role/test_eks_node"
      "username": "system:node:{{EC2PrivateDNSName}}"
    - "groups":
      - "system:masters"
      "rolearn": "arn:aws:iam::1234567890:role/test_eks_user"
      "username": "admin:{{SessionName}}"
  mapUsers: |
    - "groups":
      - "system:masters"
      "userarn": "arn:aws:iam::1234567890:user/cicd"
      "username": "cicd"

```

### Version Information
Terraform version: v1.1.4
AWS EKS provider version: v4.67.0

### Steps to Reproduce
Rotate IAM user credentials associated with the AWS EKS cluster.
Run Terraform plan or apply.

### Expected Behavior
Terraform should successfully recognize the IAM user with the updated credentials and apply changes accordingly.

### Actual Behavior
Terraform fails with the following error:

```
│ Error: Get "http://localhost/api/v1/namespaces/kube-system/configmaps/aws-auth": dial tcp 127.0.0.1:80: connect: connection refused
│ 
│   with module.eks.kubernetes_config_map.aws_auth[0],
│   on .terraform/modules/eks/main.tf line 453, in resource "kubernetes_config_map" "aws_auth":
│  453: resource "kubernetes_config_map" "aws_auth" {
```

### Workaround 
I have to update the Kubernetes provider to use config_path instead of exec plugin from my local and fix this error before running it on the cicd pipeline.
