### ISSUE TITLE
worker nodes not joining cluster after applying config-map-aws-auth.yaml

### ISSUE THREAD

**Issue by pkelleratwork** [terraform-aws-modules/terraform-aws-eks#304]
# I have issues

## I'm submitting a...

* [X] bug report
* [ ] feature request
* [ ] support request
* [X] kudos, thank you, warm fuzzy

## What is the current behavior
nodes create, confimap created, kubeconfig created. after changing to new context using new kubeconfig, tried applying the configmap for aws-auth. this is applied, but worker nodes fail to join cluster.
```
(⎈ testeks2:)➜  testeks ✗ kubectl get configmaps -n kube-system
NAME                                 DATA   AGE
aws-auth                             3      1m
coredns                              1      15m
extension-apiserver-authentication   5      15m
kube-proxy                           1      15m
```

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::xxxxxxxxx:role/testeks220190313015023961900000005
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes


  mapUsers: |

  mapAccounts: |
```

## If this is a bug, how to reproduce? Please include a code sample if relevant.
```
provider "aws" {
  region = "us-east-1"
  version = "~> 2.0"
}

module "eks" {
  source  = "terraform-aws-modules/eks/aws"
  version = "2.2.1"

  # the 3 required variables here
  cluster_name = "testeks2"
  subnets = ["subnet-x", "subnet-xx", "subnet-xxx"]
  vpc_id = "vpc-xxxxx"
  # not required
  cluster_version = "1.11"
  config_output_path = "./"
  kubeconfig_name = "testeks2"
  manage_aws_auth = "false"
  tags = {
    environment = "dev"
    cluster = "testeks2"
  }
  worker_groups = [
    {
      asg_desired_capacity = 3
      asg_max_size  = 50
      instance_type = "t2.micro"
      autoscaling_enabled = "true"
    }
  ]
}
```

## What's the expected behavior?
worker nodes should join cluster.

## Environment details

* Affected module version:
* OS:
* Terraform version:
terraform 0.11.11
provider ~>2.0
module 
	source terraform-aws-modules/eks/aws  version 2.2.21

## Any other relevant info
i like ben & jerrys phish food ice cream
