### ISSUE TITLE
Worker nodes are not joining the cluster using version 2.3.0

### ISSUE THREAD

**Issue by armandorvila** [terraform-aws-modules/terraform-aws-eks#310]
# I have issues
While creating a new cluster using the version 2.3.0 of the module and the AMI `ami-01e08d22b9439c15a` for the worker nodes, not a single worker node joins the cluster. 
## I'm submitting a...

* [x] bug report
* [ ] feature request
* [ ] support request
* [ ] kudos, thank you, warm fuzzy

## What is the current behaviour?

* The EKS cluster is created, the autoscaling group, the lunch configuration and nodes are created. However, when running kubectl get nodes there are no nodes at all. 

* Running cat /var/lib/kubelet/kubeconfig within any of the worker nodes, we can see a miss-configuration issue: 

```
apiVersion: v1
clusters:
- cluster:
    certificate-authority: /etc/kubernetes/pki/ca.crt
    server: https://<Skipping this part>.sk1.eu-west-1.eks.amazonaws.com
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: kubelet
  name: kubelet
current-context: kubelet
kind: Config
preferences: {}
users:
- name: kubelet
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      args:
      - token
      - -i
      - --enable-docker-bridge
      command: /usr/bin/aws-iam-authenticator
      env: null
```

Instead of the cluster name, after the `-i` option we are getting `--enable-docker-bridge`

## If this is a bug, how to reproduce? Please include a code sample if relevant.

Create a new cluster using the 2.3.0 version of the module and the AMI `ami-01e08d22b9439c15a` and run:
```
kubectl get nodes
```
SSH into one of the worker nodes and run:
```
cat /var/lib/kubelet/kubeconfig
```
## What's the expected behaviour?

Worker nodes joining the cluster properly, just like they do with the version 2.2.1 of the module.

## Environment details

* Affected module version: 2.3.0
* OS: Mac OS and Linux Alpine
* Terraform version: 0.11.13.
