### ISSUE TITLE
Not able to found disable-default-addons configuration - EKSCTL vs Terraform

### ISSUE THREAD

**Issue by leo-the-nardo** [terraform-aws-modules/terraform-aws-eks#3145]
Im trying to setup eks +cilium with terraform without kubeproxy but it always comes installed
I cant find a equivalent of "disableDefaultAddons" eksctl config in eks terraform
```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: cluster1
  region: ap-south-1
  version: "1.29"

iam:
  withOIDC: true

addonsConfig:
  disableDefaultAddons: true # <----- this line
addons:
  - name: coredns
```
