### ISSUE TITLE
CloudInit cloudinit_post_nodeadm not executing

### ISSUE THREAD

**Issue by shulyakav** [terraform-aws-modules/terraform-aws-eks#3178]
Module version: 20.24.3

Terraform version: Terraform v1.4.6 

Provider version(s):
```
+ provider registry.terraform.io/hashicorp/aws v5.71.0
+ provider registry.terraform.io/hashicorp/cloudinit v2.3.5
+ provider registry.terraform.io/hashicorp/null v3.2.3
+ provider registry.terraform.io/hashicorp/time v0.12.1
+ provider registry.terraform.io/hashicorp/tls v4.0.6
```

Reproduction Code:
```
The example code has been taken from the [official example for EKS AL2023](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/examples/eks-managed-node-group/eks-al2023.tf).
```

```
module "eks" {
  source  = "terraform-aws-modules/eks/aws"
  version = "~> 20.0"

  cluster_name    = local.name
  cluster_version = "1.30"

  # EKS Addons
  cluster_addons = {
    coredns                = {}
    eks-pod-identity-agent = {}
    kube-proxy             = {}
    vpc-cni                = {}
  }

  vpc_id     = module.vpc.vpc_id
  subnet_ids = module.vpc.private_subnets
  enable_cluster_creator_admin_permissions = true

  eks_managed_node_groups = {
    sandbox_nodegroup_4 = {
      cloudinit_post_nodeadm = [{
        content      = <<-EOT
        echo "All done"
        EOT
        content_type = "text/x-shellscript; charset=\"us-ascii\""
      }]
      
      instance_types = ["t3.micro"]
      min_size       = 1
      max_size       = 3
      desired_size   = 1
    }
  }
}
```

Steps to Reproduce:
```
Apply the above configuration using terraform apply.
After the node group is created, check /var/log/cloud-init-output.log on the EC2 instance.
The expected output of the script (echo "All done") does not appear in the logs, and the user data does not seem to include this script.
```

Current User Data:
```
MIME-Version: 1.0
Content-Type: multipart/mixed; boundary="//"

--//
Content-Type: application/node.eks.aws

---
apiVersion: node.eks.aws/v1alpha1
kind: NodeConfig
spec:
  cluster:
    apiServerEndpoint: https://******.gr7.us-west-2.eks.amazonaws.com
    certificateAuthority: L****S0K
    cidr: 172.20.0.0/16
    name: shuliak-test
  kubelet:
    config:
      maxPods: 4
      clusterDNS:
      - 172.20.0.10
    flags:
    - "--node-labels=eks.amazonaws.com/sourceLaunchTemplateVersion=1,eks.amazonaws.com/nodegroup-image=ami-0dea10283ef274270,eks.amazonaws.com/capacityType=ON_DEMAND,eks.amazonaws.com/nodegroup=sandbox_nodegroup_4-20241015001301400000000007,eks.amazonaws.com/sourceLaunchTemplateId=lt-0d29ee9bce5031ad9"
```
--//--
Expected Behavior:
I expect to see echo "All done" in /var/log/cloud-init-output.log after applying the cloudinit_post_nodeadm script.

Actual Behavior:
The node registers in the cluster successfully, but the script defined in cloudinit_post_nodeadm is not executed, and no output from echo "All done" is found in /var/log/cloud-init-output.log.

Workspaces: No
Local Cache Cleared: Yes
Additional Notes:
It seems the user data processed by the EC2 instance does not contain the cloudinit_post_nodeadm script. This might indicate an issue with how cloudinit_post_nodeadm is being handled in the module for EKS-managed node groups.

Please advise if there are any additional steps required to ensure that the cloudinit_post_nodeadm scripts are correctly executed.
