### ISSUE TITLE
AWS Profile in kubeconfig template

### ISSUE THREAD

**Issue by mschuchard** [terraform-aws-modules/terraform-aws-eks#39]
## I'm submitting a

* [x] feature request

For my current delivery, the customer has credentials with multiple profiles and not only needs to specify different profiles per cluster, but has no `default` profile.

It would be great if the `kubeconfig.tpl` could be modified:

```yaml
...
users:
- name: aws
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      command: heptio-authenticator-aws
      args:
        - "token"
        - "-i"
        - "${cluster_name}"
      env:
        - name: AWS_PROFILE
          value: ${aws_profile}
```

where the default Terraform value to populate the template would be `default` to ensure no regression.

I wanted to start a discussion before a PR to ensure best path forward on this. Thanks!
