### ISSUE TITLE
Configure the Cluster's Loadbalancer

### ISSUE THREAD

**Issue by paulpog-arachnys** [terraform-aws-modules/terraform-aws-eks#433]
# I have issues

## I'm submitting a...

* [ ] bug report
* [ ] feature request
* [x ] support request
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?
Currently when using the following .tf file the module creates a loadbalancer that references the worker nodes. However, it creates both port 80 (HTTP) and 443 (HTTPS) listeners, and the HTTPS listener won't work because there is no certificate associated with it.

.tf snippet:
locals {
  subnets = "${data.terraform_remote_state.environment.subnets.public_subnets}"
  vpc_id  = "${data.terraform_remote_state.environment.vpc_id}"
  worker_groups = [
    {
      # This will launch an autoscaling group with only On-Demand instances
      asg_max_size         = "${var.asg_desired_capacity}"
      instance_type        = "${var.instance_type}"
      subnets              = "${join(",", local.subnets)}"
      asg_desired_capacity = "${var.asg_desired_capacity}"
      autoscaling_enabled   = true
    },
  ]
}

output "vpc_subnets" {
  value = "${data.terraform_remote_state.environment.subnets}"
}

output "vpc_id" {
  value = "${data.terraform_remote_state.environment.vpc_id}"
}

module "eks" {
  source        = "github.com/terraform-aws-modules/terraform-aws-eks?ref=v4.0.2"
  cluster_name  = "${var.environment}"
  subnets       = "${local.subnets}"
  vpc_id        = "${local.vpc_id}"
  worker_groups = "${local.worker_groups}"
  manage_aws_auth = "true"
}

## What's the expected behavior?
The documentation gives no way of configuring the load balancer to say:
1. only use port 443, or any other port you need
2. attach a certificate to the HTTPS port
3. route to another SG instead of the instances

## Are you able to fix this problem and submit a PR? Link here if you have already.
No
## Environment details

* Affected module version: 4.0.2
* OS: Ubuntu 16.04 LTS
* Terraform version: 0.11.13

**Comment by max-rocket-internet** [comment]
I suggest you let k8s create the ELB: https://kubernetes.io/docs/concepts/services-networking/service/#loadbalancer

I use these annotations to select a certificate from ACM and terminate SSL on the ELB:

```yaml
      service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:ap-southeast-1:99999999:certificate/aaa-sddddd-ggggg
      service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
      service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
```

Maybe have a read of this also: https://kubernetes.io/docs/tutorials/kubernetes-basics/expose/expose-intro/

🙂

**Comment by paulpog-arachnys** [comment]
Thanks @max-rocket-internet .
But i'm a little confused.
I take it these configs are to be applied via kubectl after this module runs?
If that is the case, how do I stop this module creating the loadbalancer?
If that isn't the case, where do these config files go in order for this module to use them?

Paul

**Comment by max-rocket-internet** [comment]
> I take it these configs are to be applied via kubectl after this module runs?

Yes. You have to manage this yourself.

> If that is the case, how do I stop this module creating the loadbalancer?

This module will not create a loadbalancer service.

> If that isn't the case, where do these config files go in order for this module to use them?

Wherever you like. Some people maintain YAML files. Some people use Helm. Creating services in k8s is not related to this module at all 🙂

**Comment by paulpog-arachnys** [comment]
`This module will not create a loadbalancer service.`
@max-rocket-internet it is creating the loadbalancer, because my work isn't ands one is created after the module runs

**Comment by ziedbouf** [comment]
i gonne throught the process of setting up jenkins-x on eks cluster it seems that if the aws account new or  you had never spin up loadbalancer aws will block spining up an ELB for eks. however all the setup works only in public subnets in the counter part on private subnets it's always in pending state whenever you have loadbalancer or not.

@paulpog-arachnys  please check the following #144 however the create_loadbalancer option was deleted due to the way AWS handles linked roles #132 and #160 

@max-rocket-internet i am using the following starter script to spin up eks and apply jx at the end however in private subnet configuration eks wasn't able to creaste a loadbalancer including all the needed tags, is it possible please to shed some lights on the roles needed for eks to have access to loadbalancer and at which stage we should apply it in the procees?

**Comment by paulpog-arachnys** [comment]
For reasons of stability, we are using 4.0.2 of the module that does create an ELB that, basically, routes  TCP on ports 80/443 to a ports on the ingress controller and lets the ingress controller deal with HTTPS.
I can handle this, by adding an TLS listener on the nginx controller and post fact remove the port 80 listener from the elb.
However, it would be nice to have the option to configure the ELB via the module.

**Comment by max-rocket-internet** [comment]
Again, I guarantee this module is not creating an ELB 😅

> that does create an ELB that, basically, routes TCP on ports 80/443 to a ports on the ingress controller and lets the ingress controller

Bingo. Your ingress controller creates a service that creates your ELB. I would suggest you read the documentation for your ingress controller to work out your TLS issue. We are using nginx-ingress installed from the [Helm chart](https://github.com/helm/charts/tree/master/stable/nginx-ingress) and we use these settings in order to use an ACM certificate and terminate SSL on the ELB:

```yaml
controller:
  service:
    targetPorts:
      https: 80
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:ap-southeast-1:99999:certificate/aaaaa-bbbb-bbbbb
      service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
      service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
```

I hope that helps 👍
