### ISSUE TITLE
Adding `map_roles` prevents worker nodes from joining cluster

### ISSUE THREAD

**Issue by Phil-Pinkowski** [terraform-aws-modules/terraform-aws-eks#494]
# I have issues

## I'm submitting a...

* [x] bug report
* [ ] feature request
* [ ] support request
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?

Adding `map_roles` to the module configuration prevents worker nodes from joining cluster

## If this is a bug, how to reproduce? Please include a code sample if relevant.

```
map_roles = [
    {
      role_arn = "arn:aws:iam::123456789:role/EKSManagement"
      username = "external-access:{{AccountID}}"
      group    = "system:masters"
    }
  ]
```

## What's the expected behavior?

Adding roles should only add additional roles, not overwrite the required roles the nodes are using

## Environment details

* Affected module version:
* OS: Linux
* Terraform version: 0.12.7

## Any other relevant info

I am seeing errors in the API server logs in cloudwatch to indicate the role the nodes are using is not mapped. This is the same issue as described in #206

**Comment by uyenle57** [comment]
I am also experiencing the same issue. I believe this is also related to #534 

In my case I use Jenkins to run Terraform to create an EKS cluster. I provided map_roles like above, and the module created the aws-auth ConfigMap and Terraform says that it's successfully applied to the cluster. However the nodes weren't able to join the cluster and I wasn't able to join the cluster.

To workaround, I had to explicitly define the Configmap as a local variable:
```
locals {
  config_map_aws_auth = <<CONFIGMAPAWSAUTH
apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: ${module.eks_cluster.cluster_iam_role_arn}
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
    - rolearn: ${module.eks_admin_role.this_iam_role_arn}
      username: KubernetesAdmin
      groups:
        - system:masters
CONFIGMAPAWSAUTH
}
```

And apply it using local-exec like this so Jenkins can apply it for me.
```
resource "null_resource" "cluster" {
  triggers = {
    configmap_trigger = local.config_map_aws_auth
  }

  provisioner "local-exec" {
    command = "kubectl --kubeconfig ./kubeconfig_${module.eks_cluster.cluster_id} apply -f -<<EOF\n${local.config_map_aws_auth}\nEOF"
  }
}
```

Please someone look into this. Thanks.

**Comment by max-rocket-internet** [comment]
> However the nodes weren't able to join the cluster

Why not?

**Comment by uyenle57** [comment]
> > However the nodes weren't able to join the cluster
> 
> Why not?

It's because the aws-auth ConfigMap wasn't applied, even though Terraform says that it is :(

**Comment by shanmugakarna** [comment]
Please review https://github.com/terraform-aws-modules/terraform-aws-eks/pull/606

**Comment by max-rocket-internet** [comment]
> I think it could be the 2 empty lines that's breaking it?

It's YAML so empty lines shouldn't make any difference.

**Comment by jonathancolby-olx** [comment]
@uyenle57 - can you maybe post the output (with sensitive data removed) of `kubectl get cm aws-auth -n kube-system -o yaml`

I also discovered a bug (will probably file a bug report here).  If you do not specify any worker groups, the aws-auth file has a syntax error `|2` (see below).    I dont think spaces are the problem however.  I removed the `2` and kept the spaces and recreated this file, and it worked.

```
kubectl get cm aws-auth -n kube-system -o yaml
apiVersion: v1
data:
  mapRoles: |2


    - "groups":
      - "system:authenticated"
      "rolearn": "arn:aws:iam::(edited)"
      "username": "'{{SessionName}}'"

kind: ConfigMap
metadata:
  creationTimestamp: "(edited)"
  name: aws-auth
  namespace: kube-system
```
