### ISSUE TITLE
Using `aws eks get-token` instead of `aws-iam-authenticator`

### ISSUE THREAD

**Issue by icy** [terraform-aws-modules/terraform-aws-eks#504]
# I have issues

I want to use `aws eks get-token`  instead of `aws-iam-authenticator` that requires to install another tool on the workstation

## I'm submitting a...

* [ ] bug report
* [x] feature request
* [ ] support request
* [ ] kudos, thank you, warm fuzzy

## What is the current behavior?

Require `aws-iam-authenticator`. There is no option to use another tool (`aws eks get-token`)

## What's the expected behavior?

Can use `aws eks get-token` as an authenticator. For example

```
users:
- name: foobar
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      command: aws
      args:
        - "eks"
        - "get-token"
        - "--cluster-name"
        - "foobar"
        - "--region"
        - "eu-west-1"

      env:
        - name: AWS_PROFILE
          value: foobar
```

## Environment details

* Affected module version:
* OS:
* Terraform version:
