### ISSUE TITLE
syntax error in generated `aws-auth` file when no workers defined

### ISSUE THREAD

**Issue by jonathancolby-olx** [terraform-aws-modules/terraform-aws-eks#661]
# I have issues

## I'm submitting a...

* [X ] bug report
* [ ] feature request
* [ ] support request - read the [FAQ](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/faq.md) first!
* [ ] kudos, thank you, warm fuzzy

## module version

7.0.1

## What is the current behavior?

 If you do not specify any worker groups, the aws-auth file has a syntax error, however you define roles in `map_roles`,  a syntax error is generated from the template file.

Notice the number 2 in the mapRoles line:

```
kubectl get cm aws-auth -n kube-system -o yaml
apiVersion: v1
data:
  mapRoles: |2


    - "groups":
      - "system:authenticated"
      "rolearn": "arn:aws:iam::role/(edited)"
      "username": "'{{SessionName}}'"

kind: ConfigMap
metadata:
  creationTimestamp: "(edited)"
  name: aws-auth
  namespace: kube-system
```

## If this is a bug, how to reproduce? Please include a code sample if relevant.

define one or more `map_roles`

keep `workers` empty (do not defined any workers)

## What's the expected behavior?

The aws-auth is generated without syntax errors, even when no worker configuration is defined (worker config is an empty list `[]` )

## Environment details

* Affected module version:
* OS:
* Terraform version:
