### ISSUE TITLE
Issues with the new eks ami cause of security groups

### ISSUE THREAD

**Issue by rverma-jm** [terraform-aws-modules/terraform-aws-eks#877]
# I have issues
I upgraded control pane on eks to 1.16 around a week back. Everything was working back then with workers on 1.15-x ami. Yesterday when we upgraded workers to 1.16-x ami everything breaks and we started receiving `host not found exception`. Somehow the dns resolution was totally broken. We have even updated the coredns, kube-proxy and aws-node also, but even with that it was no luck.

We then created a managed node group through this module only and dns resolution was working on those instances.
We found that the fix was to attach eks generated control pane security group `eks-cluster-sg-<cluster_name>-93166555` to all instances.

## I'm submitting a...

* [x] bug report

## What is the current behavior?
Currently this modules generates 3 security groups
1. Default control pane eni one which looks like `eks-cluster-sg-<cluster_name>-93166555`
<img width="1450" alt="Screenshot 2020-05-12 at 7 13 12 AM" src="https://user-images.githubusercontent.com/58203822/81629234-4d99a280-9420-11ea-8f08-59b86f44e7e4.png">

2. Additional control pane security group, which looks like `<cluster_name>**1`
<img width="1792" alt="Screenshot 2020-05-12 at 6 45 18 AM" src="https://user-images.githubusercontent.com/58203822/81628173-956afa80-941d-11ea-9770-e8a0b455a735.png">

3. Additional worker security group, which looks like `<cluster_name>**5`
<img width="1435" alt="Screenshot 2020-05-12 at 7 13 02 AM" src="https://user-images.githubusercontent.com/58203822/81629223-48d4ee80-9420-11ea-8d5b-38793d246f21.png">

Although when we create a managed nodegroup, it only uses control pane security group with no option to modify. It didn't even uses the additional control pane security group too.
<img width="1792" alt="Screenshot 2020-05-12 at 6 53 12 AM" src="https://user-images.githubusercontent.com/58203822/81628197-9ef46280-941d-11ea-8093-446e754a5708.png">

## If this is a bug, how to reproduce? Please include a code sample if relevant.
Can be simulated by upgrading worker group ami to latest ami on any workload which needs outside kubernetes dns resolution.

## What's the expected behavior?
Its more of a proposal than an expected behaviour
1. Discard default generated control pane security group, or make it optional. This will be a breaking change since it will force to recreate the eks cluster. 
2. Default assign eks-control pane sg to all worker nodes in additional to worker node group. Probably we can get rid of duplicate rules. 
3. Optionally move the logic of eks-control-pane security group to worker templates rather than cluster. This allows us to create/ assign security groups as per the worker groups. Since we already have a eks-cluster-pane's default, this can't limit intra node connectivity but it would be helpful in determining whether this nodegroup has access to this db etc...

## Environment details

* Affected module version: all
* OS: macos
* Terraform version: 0.12.24

**Comment by dpiddockcmp** [comment]
I haven't been able to reproduce this.

I created a new cluster using the v12.0.0 [launch_templates](https://github.com/terraform-aws-modules/terraform-aws-eks/tree/v12.0.0/examples/launch_templates) example.

It creates two launch template groups:
```
$ aws ec2 describe-launch-templates --query "LaunchTemplates[].[LaunchTemplateName,LatestVersionNumber]" --output text
test-eks-lt-XE4bXcwo-worker-group-12020051613124710700000000c   3
test-eks-lt-XE4bXcwo-worker-group-22020051613124710730000000e   3
```

These are running the latest AMI in us-east-1:
```
$ aws ec2 describe-launch-template-versions --launch-template-name test-eks-lt-XE4bXcwo-worker-group-12020051613124710700000000c --versions 3 --query "LaunchTemplateVersions[].LaunchTemplateData.ImageId" --output text
ami-05ac566a7ec2378db
$ aws ec2 describe-images --image-ids ami-05ac566a7ec2378db --query "Images[].Name" --output text
amazon-eks-node-1.16-v20200507
```

And the security groups attached is the one created by the module:
```
$ aws ec2 describe-launch-template-versions --launch-template-name test-eks-lt-XE4bXcwo-worker-group-12020051613124710700000000c --versions 3 --query "LaunchTemplateVersions[].LaunchTemplateData.NetworkInterfaces[].Groups" --output text
sg-091c9c61274700e5d
```

Your issue is with outbound traffic from workers. The default rule allows all outbound traffic:
```
$ aws ec2 describe-security-groups --group-ids sg-091c9c61274700e5d --query "SecurityGroups[].[GroupName,IpPermissionsEgress[].IpRanges[].CidrIp]" --output text
test-eks-lt-XE4bXcwo20200516131242896500000006
0.0.0.0/0
```

```
$ kubectl --kubeconfig kubeconfig_test-eks-lt-XE4bXcwo create deploy test --image=nginx:alpine
deployment.apps/test created
$ kubectl --kubeconfig kubeconfig_test-eks-lt-XE4bXcwo get po -o name
pod/test-579f685fbd-45vdj
$ kubectl --kubeconfig kubeconfig_test-eks-lt-XE4bXcwo exec -it test-579f685fbd-45vdj /bin/sh
/ # wget -O /dev/null https://www.google.com
Connecting to www.google.com (142.250.31.103:443)
saving to '/dev/null'
null                 100% |************************************| 12778  0:00:00 ETA
'/dev/null' saved
```

We have production clusters running this version of the module although we're not using the Launch Templates.

**Comment by terry-sm** [comment]
@dpiddockcmp I don't think the example you used would duplicate the the issue that @rverma-jm observed. To do so, you have to provision both managed node groups and workers. 

If you used the launch templates example AND provisioned managed node groups, you should see it. I duplicate it locally with the 12.0.0 module. Using something approximating this:

```hcl
module "cluster" {
  source  = "terraform-aws-modules/eks/aws"
  version = "= 12.0.0"

  vpc_id  = var.vpc_id
  subnets = var.subnets

  cluster_name                    = var.name
  cluster_version                 = "1.16"
  cluster_endpoint_private_access = true

  enable_irsa = true

  node_groups_defaults = {
    ami_type  = "AL2_x86_64"
    disk_size = 50
  }

  node_groups = {
    example = {
      desired_capacity = 2
      max_capacity     = 10
      min_capacity     = 2

      instance_type = "m5.large"
    }
  }

  worker_groups = [
    {
      name                 = "worker-group-large"
      instance_type        = "t3.large"
      asg_desired_capacity = 3
    }
  ]

  worker_groups_launch_template = concat([
    {
      name                 = "worker-group-1"
      instance_type        = "t2.small"
      asg_desired_capacity = 2
    },
    {
      name                 = "worker-group-2"
      instance_type        = "t2.medium"
      asg_desired_capacity = 1
    }
  ]

  manage_aws_auth = true
  map_roles       = var.map_roles
  map_accounts    = var.map_accounts
  map_users       = var.map_users

  tags = var.tags
}

```

Updating the CoreDNS deployment to bind to the Node Group using affinities:

```
$ kubectl edit deployment -n kube-system coredns
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
...
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
               - key: eks.amazonaws.com/nodegroup
                  operator: Exists
```

And deploying two Pods to test DNS: one to worker and the other to a nodegroup:

```yaml
---
apiVersion: v1
kind: Pod
metadata:
  name: dnsutils-worker
  namespace: default
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key: eks.amazonaws.com/nodegroup
              operator: DoesNotExist
  containers:
  - name: dnsutils
    image: gcr.io/kubernetes-e2e-test-images/dnsutils:1.3
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
  restartPolicy: Always
---
apiVersion: v1
kind: Pod
metadata:
  name: dnsutils-nodegroup
  namespace: default
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key: eks.amazonaws.com/nodegroup
              operator: Exists
  containers:
  - name: dnsutils
    image: gcr.io/kubernetes-e2e-test-images/dnsutils:1.3
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
  restartPolicy: Always

```

And testing resolution.

```
$ kubectl exec -ti dnsutils-nodegroup -- nslookup kubernetes.default
Server:         10.100.0.10
Address:        10.100.0.10#53

Name:   kubernetes.default.svc.cluster.local
Address: 10.100.0.1

$ kubectl exec -ti dnsutils-worker -- nslookup kubernetes.default
;; connection timed out; no servers could be reached

command terminated with exit code 1
exit status 1
```
